# Generated by Django 2.1.5 on 2019-06-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_updates',
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_backers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
