# Generated by Django 2.2.2 on 2019-06-07 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='funded_project',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owned_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status_updates',
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('tech', 'tech'), ('comics', 'comics'), ('game', 'game'), ('food', 'food'), ('music', 'music')], default='tech', max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_backers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
