# Generated by Django 2.2.2 on 2019-06-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0002_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crowdfunder.Reward'),
        ),
    ]
