# Generated by Django 2.2.2 on 2019-06-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0003_auto_20190607_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('tech', 'tech'), ('comics', 'comics'), ('game', 'game'), ('food', 'food'), ('music', 'music')], default='tech', max_length=6),
        ),
    ]
